version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mufaka/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: mufaka/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles/
  gateway:
    image: mufaka/kittygram_gateway
    ports:
      - '9000:80'
    volumes:
      - static:/app/static/
      - media:/app/static/media/
