version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: postgre_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    container_name: frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    container_name: nginx
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
