version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: mufaka/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_production:/app/media
    depends_on:
      - db

  frontend:
    image: mufaka/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  gateway:
    image: mufaka/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_production:/media
    ports:
      - 9000:80
    depends_on:
      - frontend